# Generated by Django 3.0.5 on 2020-04-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonDetails',
            new_name='PersonDetail',
        ),
    ]
